In [1]:
#!python -m pip install -U faker

In [2]:
# import pandas for structuring the data
import pandas as pd

# import numpy for numerical analysis
import numpy as np

# import libs for diagrams inline with the text
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# other utilities
from sklearn import datasets, preprocessing, metrics

from faker import Faker
import urllib.request as request
import json 
import contextlib

import requests

In [3]:
##Download the MS Excel file provided to you by the instructor. It contains the real
#SOFT 2023spring data

# read the Excel file from your data folder into a data frame
df = pd.read_excel('../data/SOFT-3.xlsx', index_col=None, na_values=['NA'])

#df.head

#del df['SOFT Internship 2023']
#df = df.iloc[1:]
#df.rename(columns = {'Unnamed: 1':'student', 'Unnamed: 2':'company'}, inplace = True)
df.head()

print(df)

                                 student                            company  \
0                       Benjamin Curovic                       Dynatest A/S
1                         Jacob Simonsen  Eriksholm Research Centre, Oticon
2                 Sebastian Godsk Hansen                           Formpipe
3             Lukas Bang Stoltz-Andersen                           Formpipe
4              Christoffer Ikizek Wegner                           Formpipe
5                             Lasse Birk                       Novo Nordisk
6       Phillip Thomas Isenborg Andersen                                PFA
7                              Sumit Dey                         Topdanmark
8   Jean-Poul Wilhelm Luplau Leth-MÃ¸ller                            KMD A/S
9                  Mathias Frank Parking                            KMD A/S
10          Magdalena Aleksandra Wawrzak                            KMD A/S
11               Mia Simone Rye de Fries                      NorthTech ApS
12                   Josef Marc Pedersen                    Alpha Solutions
13                      Frederik Bo Dahl                    Alpha Solutions
14                Matti Ben Serup Hansen                             Dafolo
15                        Kenneth Hansen                             Dafolo
16               Sebastian James Bentley                         Nuuday A/S
17                  Frederik Keis Dinsen                         Nuuday A/S
18               Daniel Gottlieb Poulsen                     Netcompany A/S

         cvr
0   40916458
1   42334219
2   29177015
3   29177015
4   29177015
5   24256790
6   13594376
7   78040017
8   26911745
9   26911745
10  26911745
11  10121361
12  27506488
13  27506488
14  61966617
15  61966617
16  40075291
17  40075291
18  14814833

In [4]:
#Anonymise people mentioned in the table by either change their names with fake
#names or scramble/encrypt them.

# Import Faker

faker = Faker()# Test fake data generation
print("The Faker library can generate fake names. By running 'faker.name()', we get:")
faker.name()

Faker.seed(4321)
dict_names = {name: faker.name() for name in df['student'].unique()}
df['student'] = df['student'].map(dict_names)


df.head(10)

The Faker library can generate fake names. By running 'faker.name()', we get:

             student                            company       cvr
0        Jason Brown                       Dynatest A/S  40916458
1        Jacob Stein  Eriksholm Research Centre, Oticon  42334219
2         Cody Brown                           Formpipe  29177015
3      Larry Morales                           Formpipe  29177015
4  Jessica Hendricks                           Formpipe  29177015
5        Brian Moore                       Novo Nordisk  24256790
6        Scott Baker                                PFA  13594376
7       Ruth Hoffman                         Topdanmark  78040017
8      Daniel George                            KMD A/S  26911745
9        David Moody                            KMD A/S  26911745

In [5]:
#Use CVRAPI () to find and extract all available data for the companies listed in the source file. 
#Store the extracted data in a file and a pandas data frame in your Python application

def cvrapi(cvr):
  request_a = request.Request(
    url='https://cvrapi.dk/api?country=dk&vat=%s' % cvr,
    headers={
      'User-Agent': 'ds-assignment'})
  with contextlib.closing(request.urlopen(request_a)) as response:
    return json.loads(response.read())


#print(data)

In [12]:
#Put all companies CVR in a list of strings
companies_cvr = df['cvr'].tolist()

#Remove duplicates
unique_cvr = [cvr for cvr in set(companies_cvr)]

print(unique_cvr)

KeyError: 'cvr'

In [ ]:
#Insert all cvr into list and afterwards download that file to pc.

#companies_json = []
#
#
#for cvr in unique_cvr:
#    companies_json.append(cvrapi(cvr))
#    
#
## Save the list to a JSON file
#with open('data.json', 'w') as f:
#    json.dump(companies_json, f)

In [ ]:
# Load the JSON file into a Python object
json_file = open("data.json", "r")
json_data = json.load(json_file)

# Convert the Python object to a Pandas DataFrame
df = pd.DataFrame.from_dict(json_data)

df.head(11)